spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mantinghao+7513
    url: jdbc:mysql://localhost:3306/springCloud_sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: dev
