spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mantinghao7513
    url: jdbc:mysql://localhost:3306/springCloud_sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
